#!/usr/bin/env node
/* Harvest spaced-repetition flashcards from the course:
   (1) glossary terms -> term/definition cards
   (2) lesson quizzes -> question / (correct answer + explanation) cards
   Output: assets/review-data.js  ->  window.GM_REVIEW = [{id, front, back, url, title, tag}]
   Pure Node, no deps. Run: node tools/build-review.js  */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

function walk(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const fp = path.join(dir, name);
    const st = fs.statSync(fp);
    if (st.isDirectory()) {
      if (['assets', 'tools', '.git', 'node_modules', 'labs'].includes(name)) continue;
      walk(fp, out);
    } else if (name.endsWith('.html')) {
      out.push(fp);
    }
  }
  return out;
}

const ENT = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'", '&nbsp;': ' ', '&times;': '×', '&minus;': '−', '&rarr;': '→', '&hellip;': '…', '&mdash;': '—', '&ndash;': '–', '&le;': '≤', '&ge;': '≥', '&asymp;': '≈', '&ne;': '≠' };
function decode(s) {
  return s.replace(/&#(\d+);/g, (_, n) => String.fromCharCode(+n))
          .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
          .replace(/&[a-z]+;/gi, m => ENT[m] != null ? ENT[m] : m);
}
function clean(html) {
  return decode(String(html).replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim();
}
function grab(block, re) { const m = block.match(re); return m ? m[1] : ''; }

const cards = [];
let quizN = 0, seen = new Set();

// ---- (1) glossary term cards ----
try {
  global.window = {};
  require(path.join(ROOT, 'assets', 'gm-glossary-data.js'));
  const terms = global.window.GM_GLOSSARY || [];
  for (const g of terms) {
    if (!g.t || !g.d) continue;
    cards.push({ id: 'g-' + g.t.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      front: g.t, back: clean(g.d), url: g.s || 'glossary.html',
      title: 'Glossary', tag: 'term' });
  }
} catch (e) { console.error('glossary load failed:', e.message); }

// ---- (2) quiz cards ----
for (const f of walk(ROOT, [])) {
  const rel = path.relative(ROOT, f).split(path.sep).join('/');
  const html = fs.readFileSync(f, 'utf8');
  const title = clean(grab(html, /<title>([\s\S]*?)<\/title>/i)).replace(/\s*[|·].*$/, '') ||
                clean(grab(html, /<h1[^>]*>([\s\S]*?)<\/h1>/i));
  // split into quiz chunks
  const parts = html.split('<div class="quiz">');
  for (let i = 1; i < parts.length; i++) {
    const block = parts[i];
    const q = clean(grab(block, /<div class="q">([\s\S]*?)<\/div>/i)).replace(/^\s*\d+[.)]\s*/, '');
    const correct = clean(grab(block, /<button class="opt"[^>]*data-c="1"[^>]*>([\s\S]*?)<\/button>/i));
    const expl = clean(grab(block, /<div class="expl">([\s\S]*?)<\/div>/i));
    if (!q || !correct) continue;
    const key = q.toLowerCase().slice(0, 60);
    if (seen.has(key)) continue; seen.add(key);
    quizN++;
    cards.push({ id: 'q-' + quizN, front: q,
      back: (expl ? correct + ' — ' + expl : correct),
      url: rel, title: title || rel, tag: 'quiz' });
  }
}

const banner = '/* AUTO-GENERATED by tools/build-review.js — do not edit by hand. */\n';
fs.writeFileSync(path.join(ROOT, 'assets', 'review-data.js'),
  banner + 'window.GM_REVIEW = ' + JSON.stringify(cards) + ';\n');

const byTag = cards.reduce((a, c) => (a[c.tag] = (a[c.tag] || 0) + 1, a), {});
console.log('review-data.js written:', cards.length, 'cards', JSON.stringify(byTag));
