#!/usr/bin/env node
/* Harvest full multiple-choice questions from lesson quizzes into an exam bank.
   Each quiz -> {id, q, opts:[...], c:correctIndex, expl, url, title, group}.
   Output: assets/exam-data.js -> window.GM_EXAM = [...]
   Pure Node, no deps. Run: node tools/build-exam.js */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

function walk(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const fp = path.join(dir, name); const st = fs.statSync(fp);
    if (st.isDirectory()) { if (['assets','tools','.git','node_modules','labs','worker'].includes(name)) continue; walk(fp, out); }
    else if (name.endsWith('.html')) out.push(fp);
  }
  return out;
}
const ENT = { '&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'",'&nbsp;':' ','&times;':'×','&minus;':'−','&rarr;':'→','&hellip;':'…','&mdash;':'—','&ndash;':'–','&le;':'≤','&ge;':'≥','&asymp;':'≈','&ne;':'≠' };
function decode(s){ return s.replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))).replace(/&[a-z]+;/gi,m=>ENT[m]!=null?ENT[m]:m); }
function clean(h){ return decode(String(h).replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim(); }
function grab(b,re){ const m=b.match(re); return m?m[1]:''; }

// url -> {group,title,num} from the search index (reused, authoritative)
let META = {};
try { global.window = {}; require(path.join(ROOT,'assets','search-data.js'));
  (global.window.GM_INDEX||[]).forEach(e=>{ META[e.url] = { group:e.group, title:e.title, num:e.num }; });
} catch(e){ console.error('index load:', e.message); }

const cards=[]; let n=0, seen=new Set();
for (const f of walk(ROOT, [])) {
  const rel = path.relative(ROOT,f).split(path.sep).join('/');
  const meta = META[rel] || {};
  const html = fs.readFileSync(f,'utf8');
  const parts = html.split('<div class="quiz">');
  for (let i=1;i<parts.length;i++){
    const block = parts[i];
    const q = clean(grab(block, /<div class="q">([\s\S]*?)<\/div>/i)).replace(/^\s*\d+[.)]\s*/, '');
    const expl = clean(grab(block, /<div class="expl">([\s\S]*?)<\/div>/i));
    const opts=[]; let correct=-1;
    const rx=/<button class="opt"([^>]*)>([\s\S]*?)<\/button>/g; let m, k=0;
    while((m=rx.exec(block))){ const isC=/data-c="1"/.test(m[1]); const txt=clean(m[2]); if(!txt) continue; if(isC) correct=k; opts.push(txt); k++; }
    if(!q || opts.length<2 || correct<0) continue;
    const key=q.toLowerCase().slice(0,60); if(seen.has(key)) continue; seen.add(key);
    n++;
    cards.push({ id:'ex-'+n, q, opts, c:correct, expl, url:rel,
      title: meta.title || rel, group: meta.group || 'Course' });
  }
}
const banner='/* AUTO-GENERATED by tools/build-exam.js — do not edit by hand. */\n';
fs.writeFileSync(path.join(ROOT,'assets','exam-data.js'), banner+'window.GM_EXAM = '+JSON.stringify(cards)+';\n');
const byGroup = cards.reduce((a,c)=>(a[c.group]=(a[c.group]||0)+1,a),{});
console.log('exam-data.js written:', cards.length, 'MCQs');
console.log('groups:', Object.keys(byGroup).length, '| sample counts:', JSON.stringify(Object.fromEntries(Object.entries(byGroup).slice(0,6))));
